-keep class com.guardian.shield.data.local.db.** { *; }
-keep class com.guardian.shield.domain.model.** { *; }
-keep class org.tensorflow.lite.** { *; }
-keepclassmembers class * { @dagger.hilt.android.* <methods>; }
-dontwarn org.tensorflow.**
